# Generated by Django 3.1.7 on 2021-03-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория', 'verbose_name_plural': '[ Категории ]'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('category', 'title'), 'verbose_name': 'Товар', 'verbose_name_plural': '[ Товары ]'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ('name',), 'verbose_name': 'Продавец', 'verbose_name_plural': '[ Продавцы ]'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
