# Generated by Django 3.1.7 on 2021-03-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0005_auto_20210325_0948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
