# Generated by Django 3.1.7 on 2021-04-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210408_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
