# Generated by Django 3.1.7 on 2021-03-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210325_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='????', max_length=50, verbose_name='Цвет'),
        ),
    ]
