# Generated by Django 3.1.7 on 2021-03-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210324_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': '[ Категории ]'},
        ),
    ]
