# Generated by Django 3.1.7 on 2021-03-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
    ]
