# Generated by Django 3.1.7 on 2021-04-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210402_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='main.Tag', verbose_name='Тэг'),
        ),
    ]
