# Generated by Django 3.1.7 on 2021-03-31 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210325_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(default='introvert', unique=True),
            preserve_default=False,
        ),
    ]
