# Generated by Django 3.1.7 on 2021-04-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210402_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=50, null=True, verbose_name='Цвет'),
        ),
    ]
