# Generated by Django 3.1.7 on 2021-04-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210402_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, default=' ', max_length=50, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
