# Generated by Django 3.1.7 on 2021-03-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_vendor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тип доставки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость')),
                ('free', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Бесплатно при сумме')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Условия доставки',
            },
        ),
    ]
