# Generated by Django 3.1.7 on 2021-04-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Пункт меню')),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(null=True, verbose_name='Текст страницы')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('id',),
            },
        ),
    ]
