# Generated by Django 3.1.7 on 2021-04-02 13:50

from django.db import migrations, models
import main.models

import ecommerce.main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210402_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=ecommerce.main.utils.path_and_rename, verbose_name='Изображение'),
        ),
    ]
