# Generated by Django 3.1.7 on 2021-04-01 21:51

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210401_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(validators=[main.models.is_adult], verbose_name='Дата рождения'),
        ),
    ]
