# Generated by Django 3.1.7 on 2021-04-02 17:55

from django.db import migrations, models
import main.models

import ecommerce.main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210402_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to=ecommerce.main.utils.upload_avatar),
        ),
    ]
