# Generated by Django 3.1.7 on 2021-04-02 18:12

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210402_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='image',
            field=models.ImageField(null=True, upload_to=main.models.upload_avatar),
        ),
    ]
