# Generated by Django 3.1.7 on 2021-04-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_parameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.CharField(blank=True, max_length=50, verbose_name='Значение'),
        ),
    ]
