# Generated by Django 3.1.7 on 2021-04-05 17:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210405_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='blank.png', null=True, upload_to=main.models.upload_avatar),
        ),
    ]
