# Generated by Django 3.1.7 on 2021-04-05 17:28

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210405_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='birthday',
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='avatar/blank.png', null=True, upload_to=main.models.upload_avatar),
        ),
    ]
