# Generated by Django 3.1.7 on 2021-04-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210405_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
