# Generated by Django 3.1.7 on 2021-04-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_customer_avatar_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
    ]
