# Generated by Django 3.1.7 on 2021-04-05 18:37

from django.db import migrations, models
import main.models

import ecommerce.main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210405_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='avatar/blank.png', null=True, upload_to=ecommerce.main.utils.upload_avatar),
        ),
    ]
